dataset: CIFAR10
model: ConvNetD5
device: [5,6]

ipc: 1
syn_steps: 40
expert_epochs: 2
lr_img: 10000
lr_teacher: 0.01

buffer_path: /mnt/hwfile/gveval/wangkai.p/buffer_storage/cifar10_convd5/

data_path: ../dataset
ema_decay: 0.995
Iteration: 10000
batch_syn: 1000

# wandb
project: LRI-DD
name: cifar10_ipc1_convd5

num_eval: 1
eval_it: 500
skip_first_eva: False

lr_y: 5.
Momentum_y: 0.9
threshold: 1.5
pix_init: samples_predicted_correctly
Sequential_Generation: False
batch_train: 128
min_start_epoch: 0
max_start_epoch: 4
lr_lr: 0.0000001
zca: True
